services:
  paxscraper:
    build: .
    container_name: paxscraper

    restart: unless-stopped

    ports:
      - "${TAILSCALE_IP}:${PORT}:${PORT}"

    volumes:
      - ./data:/app/data
      - ./products.yaml:/app/products.yaml:ro

    environment:
      - TZ=Europe/Amsterdam